version: '3.4'

services:
#  nginx:
#    image: nginx:alpine
#    volumes:
#       - ./ssl/server.key:/etc/ssl/server.key
#       - ./ssl/server.crt:/etc/ssl/server.crt
#       - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#      - "443:443"
  resourceconfiguration.api: 
    image: ${DOCKER_REGISTRY-}resourceconfigurationapi
    environment:
        - MYSQLCONNSTR=Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_resource;
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webserver.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USER=admin
        - RABBITMQ_PASS=adminPw
        - RABBITMQ_RETRY=5
        - ASPNETCORE_ENVIRONMENT=Development
        - APPSETTING_BACKGROUND_DELAY_SEC=300
        - APPSETTING_DATA_URL="https://localhost:10010/api/news/"
    build:
      context: .
      dockerfile: Services/ResourceConfiguration/ResourceConfiguration.API/Dockerfile
    ports:
      - "10000:443"
    volumes:
      - ./ssl/webserver.pfx:/https/webserver.pfx
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    environment:
        - MYSQLCONNSTR=Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_user;
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webserver.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
    ports:
      - "10005:443"
    volumes:
       - ./ssl/webserver.pfx:/https/webserver.pfx
  news.api:
    image: ${DOCKER_REGISTRY-}newsapi
    environment:
        - MYSQLCONNSTR=Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_data;
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webserver.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
    build:
      context: .
      dockerfile: Services/News/News.API/Dockerfile
    volumes:
       - ./ssl/webserver.pfx:/https/webserver.pfx
    ports:
      - "10010:443"
#  collector.api:
#    image: ${DOCKER_REGISTRY-}collectorapi
#    environment:
#        - RABBITMQ_USER=admin
#        - RABBITMQ_PASS=adminPw
#        - RABBITMQ_HOST=rabbitmq
#    build:
#      context: ./Services/NewsSimilarity/
#      dockerfile: ./Dockerfile
#    ports:
#      - "10015:5000"

  reader.api:
    image: ${DOCKER_REGISTRY-}readerapi
    build:
      context: .
      dockerfile: Services/Reader/Reader.API/Dockerfile
  writer.api:
    image: ${DOCKER_REGISTRY-}writerapi
    build:
      context: .
      dockerfile: Services/Writer/Writer.API/Dockerfile

