version: '3.4'

services:
  database:
    restart: always
    container_name: database
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: admin
    volumes:
       - ./Database:/var/lib/mysql
    ports:
      - "4000:3306"
  resourceconfiguration.api:
    image: ${DOCKER_REGISTRY-}resourceconfigurationapi
    environment:
        MYSQLCONNSTR_CONN:"Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_resource;"
    build:
      context: .
      dockerfile: Services/ResourceConfiguration/ResourceConfiguration.API/Dockerfile
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    environment:
        MYSQLCONNSTR_CONN:"Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_user;"
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
  news.api:
    image: ${DOCKER_REGISTRY-}newsapi
    environment:
        MYSQLCONNSTR_CONN:"Server=127.0.0.1;user id=root;password=admin;database=news_aggregator_data;"
    build:
      context: .
      dockerfile: Services/News/News.API/Dockerfile
